// SPDX-License-Identifier: Apache-2.0

export const MUTATION_METHODS = [
  // JavaScript/TypeScript
  'push',
  'pop',
  'shift',
  'unshift',
  'splice',
  'sort',
  'reverse',
  'fill',
  'copyWithin',
  'delete',
  'clear',
  'set',
  'add',
  // Python
  'append',
  'extend',
  'insert',
  'remove',
  'clear',
  'discard',
  'update',
  // C#
  'Add',
  'Remove',
  'RemoveAt',
  'RemoveAll',
  'Insert',
  'Sort',
  'Reverse',
  'AddRange',
  'InsertRange',
  'RemoveRange',
  'Push',
  'Pop',
  'Enqueue',
  'Dequeue',
  // Java
  'addAll',
  'removeAll',
  'retainAll',
  'put',
  'putAll',
  'replaceAll',
  'shuffle',
  // Rust (checked inline in validator with regex)
  'push',
  'pop',
  'insert',
  'remove',
  'clear',
  'append',
  'extend',
  'drain',
  'split_off',
  'truncate',
  'swap_remove',
  // Ruby (passed inline to checkMutationMethods)
  '<<',
  'push',
  'pop',
  'shift',
  'unshift',
  'insert',
  'delete',
  'delete_at',
  'delete_if',
  'clear',
  'concat',
  'replace',
  'fill',
  'sort!',
  'reverse!',
  'shuffle!',
  'rotate!',
  'compact!',
  'flatten!',
  'uniq!',
  'map!',
  'select!',
  'reject!',
  // PHP (checked inline in validator with regex)
  'array_push',
  'array_pop',
  'array_shift',
  'array_unshift',
  'array_splice',
  'sort',
  'rsort',
  'asort',
  'arsort',
  'ksort',
  'krsort',
  'usort',
  'uasort',
  'uksort',
  'shuffle',
  'array_walk',
  'array_walk_recursive',
  // Go (not applicable - Go doesn't have methods on slices, uses built-in functions)
  // Mutations handled via: append(), copy(), and direct slice assignment
];
